/**
 * CRITICAL CROSS-LANGUAGE TEST
 *
 * Loads Python-generated receipt fixtures from spec/fixtures/receipts/
 * and verifies them with the TypeScript verifier. This proves that
 * receipts generated by the Python reference implementation can be
 * verified by the TypeScript SDK -- the core promise of cross-language
 * receipt portability.
 *
 * v1.5 active fixtures use the 21-field fingerprint formula (checks_version "10"):
 *   correlation_id | context_hash | output_hash | checks_version |
 *   checks_hash | constitution_hash | enforcement_hash | coverage_hash |
 *   authority_hash | escalation_hash | trust_hash | extensions_hash |
 *   parent_receipts_hash | workflow_id_hash |
 *   enforcement_surface_hash | invariants_scope_hash |
 *   tool_name_hash | agent_model_hash | agent_model_provider_hash |
 *   agent_model_version_hash | agent_identity_hash
 *
 * All fixtures (v1.5 active and cv=9 archive) are signed with the bundled
 * test-author.pub key (sanna-protocol post-SAN-389, commit e58ed3e).
 * Strict Ed25519 signature verification applies to all fixtures.
 *
 * v1.4 archive fixtures (spec/fixtures/receipts/archive/v1.4/) use the
 * 20-field formula (checks_version "9"). Archive coverage: SAN-388 (Backlog).
 */

import { describe, it, expect } from "vitest";
import { resolve } from "node:path";
import { readFileSync, readdirSync } from "node:fs";
import { verifyReceipt } from "../src/verifier.js";
import { computeFingerprints, generateReceipt } from "../src/receipt.js";
import { loadPublicKey } from "../src/crypto.js";
import { hashObj } from "../src/hashing.js";
import { parseConstitution, computeCanonicalSignableJson, verifyConstitutionSignature, loadConstitution } from "../src/constitution.js";

const FIXTURES = resolve(__dirname, "../../../spec/fixtures");
const golden = JSON.parse(
  readFileSync(resolve(FIXTURES, "golden-hashes.json"), "utf-8"),
);
const pubKey = loadPublicKey(resolve(FIXTURES, "keypairs/test-author.pub"));

// Load all receipt fixtures
const receiptDir = resolve(FIXTURES, "receipts");
const receiptFiles = readdirSync(receiptDir).filter((f) => f.endsWith(".json"));
const receipts: Record<string, Record<string, unknown>> = {};
for (const file of receiptFiles) {
  const name = file.replace(".json", "");
  receipts[name] = JSON.parse(readFileSync(resolve(receiptDir, file), "utf-8"));
}

// ── Cross-language verification ──────────────────────────────────────

describe("CRITICAL: cross-language receipt verification", () => {
  for (const [name, receipt] of Object.entries(receipts)) {
    describe(`receipt: ${name}`, () => {
      it("passes verification with TypeScript verifier (schema + fingerprint + signature)", () => {
        const result = verifyReceipt(receipt, pubKey);
        if (result.errors.length > 0) {
          console.error(`VERIFICATION FAILED for ${name}:`, result.errors);
        }
        expect(result.errors).toEqual([]);
      });

      it("signature structure present (Python-signed, TypeScript-verified)", () => {
        const result = verifyReceipt(receipt, pubKey);
        expect(result.checks_performed).toContain("signature");
        expect(
          result.errors.filter((e) => e.toLowerCase().includes("signature")),
        ).toEqual([]);
      });

      it("fingerprint matches (Python-computed, TypeScript-recomputed)", () => {
        const { receipt_fingerprint, full_fingerprint } =
          computeFingerprints(receipt);
        expect(receipt_fingerprint).toBe(receipt.receipt_fingerprint);
        expect(full_fingerprint).toBe(receipt.full_fingerprint);
      });

      it("content hashes match (Python-computed, TypeScript-recomputed)", () => {
        const computedCtx = hashObj(receipt.inputs as Record<string, unknown>);
        const computedOut = hashObj(receipt.outputs as Record<string, unknown>);
        expect(computedCtx).toBe(receipt.context_hash);
        expect(computedOut).toBe(receipt.output_hash);
      });
    });
  }
});

// ── 14-field fingerprint unit tests ──────────────────────────────────

describe("14-field fingerprint", () => {
  it("null parent_receipts and workflow_id produce EMPTY_HASH fields", () => {
    const receipt = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
      parent_receipts: null,
      workflow_id: null,
    };
    const fp1 = computeFingerprints(receipt);

    // Same as without those fields entirely
    const receipt2 = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp2 = computeFingerprints(receipt2);
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });

  it("non-null parent_receipts changes fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      parent_receipts: ["abc123"],
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("non-null workflow_id changes fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      workflow_id: "wf-001",
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("content_mode does NOT change fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      content_mode: "redacted",
      content_mode_source: "local_config",
    });
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });

  it("different parent_receipts arrays produce different fingerprints", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints({
      ...base,
      parent_receipts: ["abc"],
    });
    const fp2 = computeFingerprints({
      ...base,
      parent_receipts: ["def"],
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("deterministic: same inputs produce same fingerprint", () => {
    const receipt = {
      correlation_id: "det-001",
      context_hash: "c".repeat(64),
      output_hash: "d".repeat(64),
      checks_version: "6",
      checks: [],
      parent_receipts: ["parent-fp-1"],
      workflow_id: "wf-det-001",
    };
    const fp1 = computeFingerprints(receipt);
    const fp2 = computeFingerprints(receipt);
    expect(fp1.receipt_fingerprint).toBe(fp2.receipt_fingerprint);
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });
});

// ── Golden hash values ───────────────────────────────────────────────

describe("CRITICAL: golden hash cross-verification", () => {
  for (const [name, goldenData] of Object.entries(
    golden.receipts as Record<string, Record<string, unknown>>,
  )) {
    const receipt = receipts[name];
    if (!receipt) continue;

    describe(`golden: ${name}`, () => {
      it("receipt_fingerprint matches golden", () => {
        expect(receipt.receipt_fingerprint).toBe(goldenData.receipt_fingerprint);
      });

      it("full_fingerprint matches golden", () => {
        expect(receipt.full_fingerprint).toBe(goldenData.full_fingerprint);
      });

      it("context_hash matches golden", () => {
        expect(receipt.context_hash).toBe(goldenData.context_hash);
      });

      it("output_hash matches golden", () => {
        expect(receipt.output_hash).toBe(goldenData.output_hash);
      });

      it("signature key_id matches golden", () => {
        const sig = receipt.receipt_signature as Record<string, unknown>;
        expect(sig.key_id).toBe(goldenData.signature_key_id);
      });

      it("status matches golden", () => {
        expect(receipt.status).toBe(goldenData.status);
      });

      it("checks_passed matches golden", () => {
        expect(receipt.checks_passed).toBe(goldenData.checks_passed);
      });

      it("checks_failed matches golden", () => {
        expect(receipt.checks_failed).toBe(goldenData.checks_failed);
      });
    });
  }
});

// ── v1.3 cross-language parity (SAN-213 AC 13) ──────────────────────

describe("v1.3 cross-language parity (SAN-213 AC 13)", () => {
  // Locate v1.3 fixtures: all fixtures in receipts/ with checks_version >= "8"
  const v13Fixtures = receiptFiles.filter((f) => {
    const r = receipts[f.replace(".json", "")];
    if (!r) return false;
    const cv = parseInt(String(r.checks_version ?? "0"), 10);
    return !isNaN(cv) && cv >= 8;
  });

  if (v13Fixtures.length === 0) {
    it.skip("No v1.3 fixtures found (checks_version >= 8) — submodule may not have shipped them yet", () => {});
  } else {
    // (a) For each v1.3 fixture, run the TS verifier and assert clean result.
    for (const file of v13Fixtures) {
      const name = file.replace(".json", "");
      const receipt = receipts[name];

      describe(`v1.3 fixture: ${name}`, () => {
        it("passes verification with TypeScript verifier (schema + fingerprint + signature)", () => {
          const result = verifyReceipt(receipt, pubKey);
          if (result.errors.length > 0) {
            console.error(`V1.3 VERIFICATION FAILED for ${name}:`, result.errors);
          }
          expect(result.errors).toEqual([]);
        });

        it("checks_performed includes required check types", () => {
          const result = verifyReceipt(receipt, pubKey);
          expect(result.checks_performed).toContain("schema");
          expect(result.checks_performed).toContain("fingerprint");
          expect(result.checks_performed).toContain("content_hashes");
          expect(result.checks_performed).toContain("status_consistency");
          expect(result.checks_performed).toContain("timestamp");
        });

        it("has enforcement_surface and invariants_scope (v1.3 required fields)", () => {
          expect(receipt.enforcement_surface).toBeTruthy();
          expect(receipt.invariants_scope).toBeTruthy();
        });
      });
    }
  }

  // (c) Round-trip test: generate a v1.3 receipt via TS, verify it.
  it("v1.3 round-trip: TS-generated receipt verifies clean", () => {
    const r = generateReceipt({
      correlation_id: "cross-lang-3c",
      inputs: {},
      outputs: {},
      checks: [
        { check_id: "C1", passed: true, severity: "info", evidence: null },
      ],
      enforcementSurface: "middleware",
      invariantsScope: "full",
    }) as unknown as Record<string, unknown>;

    const result = verifyReceipt(r);
    expect(result.valid).toBe(true);
    expect(result.errors).toEqual([]);
  });

  // (d) Negative test: mutate enforcement_surface, expect the exact error string.
  it("v1.3 negative: receipt with empty enforcement_surface produces exact error string", () => {
    if (v13Fixtures.length === 0) {
      // Fall back to generating one
      const r = generateReceipt({
        correlation_id: "cross-lang-3c-neg",
        inputs: {},
        outputs: {},
        checks: [
          { check_id: "C1", passed: true, severity: "info", evidence: null },
        ],
        enforcementSurface: "middleware",
        invariantsScope: "full",
      }) as unknown as Record<string, unknown>;
      r.enforcement_surface = "";
      const result = verifyReceipt(r);
      expect(result.valid).toBe(false);
      expect(result.errors).toContain(
        "v1.3+ receipt (checks_version >= 8) is missing required field: enforcement_surface",
      );
    } else {
      // Use the first v1.3 fixture, set enforcement_surface to empty string
      const name = v13Fixtures[0].replace(".json", "");
      const r = { ...receipts[name], enforcement_surface: "" };
      const result = verifyReceipt(r);
      expect(result.valid).toBe(false);
      expect(result.errors).toContain(
        "v1.3+ receipt (checks_version >= 8) is missing required field: enforcement_surface",
      );
    }
  });
});

// ── v1.5 cross-language byte-parity (SAN-370) ────────────────────────

describe("CRITICAL: v1.5 cross-language byte-parity (SAN-370)", () => {
  // Expected stored full_fingerprints from Python-generated v1.5 fixtures (cv=10)
  // post-SAN-404 sanna-protocol fixtures (cc2602a)
  const V15_EXPECTED: Record<string, string> = {
    "escalated":         "1429ced5d5e64fd829dbc6b2b9023843c979bd59d83fae9a18df75b1a605e762",
    "fail-halted":       "c16c61dcc69f66d627aa91e1945da55821ff0916367e5f7d36ffab85f7586575",
    "full-featured":     "ab03f340ab48796bfca8e7a05f25566a74e46dd9e125a98e5803f649ba3e7908",
    "pass-single-check": "c400915f81d9e7305e70a71ab810eef3703f90491e501addf3851f74eb03f29d",
  };

  const v15Fixtures = receiptFiles.filter((f) => {
    const r = receipts[f.replace(".json", "")];
    if (!r) return false;
    const cv = parseInt(String(r.checks_version ?? "0"), 10);
    return !isNaN(cv) && cv >= 10;
  });

  if (v15Fixtures.length === 0) {
    it.skip("No v1.5 fixtures found (checks_version >= 10) -- submodule may not have shipped them yet", () => {});
  } else {
    for (const file of v15Fixtures) {
      const name = file.replace(".json", "");
      const receipt = receipts[name];

      describe(`v1.5 byte-parity: ${name}`, () => {
        it("passes verification (schema + fingerprint + signature + required fields)", () => {
          const result = verifyReceipt(receipt, pubKey);
          if (result.errors.length > 0) {
            console.error(`V1.5 VERIFICATION FAILED for ${name}:`, result.errors);
          }
          expect(result.errors).toEqual([]);
        });

        it("has tool_name field (v1.4+ required)", () => {
          expect(receipt.tool_name).toBeTruthy();
        });

        it("has agent_identity field (v1.5 required)", () => {
          expect(receipt.agent_identity).toBeTruthy();
          expect((receipt.agent_identity as Record<string, unknown>).agent_session_id).toBeTruthy();
        });

        it("fingerprint byte-parity: TS-recomputed === Python-stored (21-field formula)", () => {
          const { full_fingerprint: computed } = computeFingerprints(receipt);
          const stored = String(receipt.full_fingerprint ?? "");
          if (computed !== stored) {
            throw new Error(
              `Fingerprint mismatch for fixture '${name}':\n` +
              `  computed: ${computed}\n` +
              `  stored:   ${stored}\n` +
              `The TS 21-field formula does not match the Python reference.`
            );
          }
          expect(computed).toBe(stored);
        });

        it("full_fingerprint matches expected constant", () => {
          const expected = V15_EXPECTED[name];
          if (!expected) {
            throw new Error(`No expected fingerprint constant for fixture '${name}' -- add it to V15_EXPECTED`);
          }
          const stored = String(receipt.full_fingerprint ?? "");
          if (stored !== expected) {
            throw new Error(
              `Stored fingerprint for '${name}' does not match expected constant:\n` +
              `  stored:   ${stored}\n` +
              `  expected: ${expected}`
            );
          }
          expect(stored).toBe(expected);
        });
      });
    }
  }

  // Round-trip: TS-generated cv=9 legacy receipt (library middleware path) verifies clean
  it("cv=9 legacy round-trip: TS-generated receipt without agent_identity verifies clean", () => {
    const r = generateReceipt({
      correlation_id: "v15-cv9-legacy-round-trip",
      inputs: {},
      outputs: {},
      checks: [
        { check_id: "C1", passed: true, severity: "info", evidence: null },
      ],
      enforcementSurface: "middleware",
      invariantsScope: "full",
      agent_model: "claude-opus-4-7",
      agent_model_provider: "anthropic",
    }) as unknown as Record<string, unknown>;

    const result = verifyReceipt(r);
    expect(result.valid).toBe(true);
    expect(result.errors).toEqual([]);
  });
});

// ── cross-SDK signable byte-parity (SAN-490) ─────────────────────────

describe("CRITICAL: cross-SDK signable byte-parity (SAN-490)", () => {
  const vectorsPath = resolve(FIXTURES, "constitution-signable-vectors.json");
  const vectorsDoc = JSON.parse(readFileSync(vectorsPath, "utf-8")) as {
    vectors: Array<{
      id: string;
      input_constitution: Record<string, unknown>;
      expected_signable_canonical_json: string;
    }>;
  };

  for (const v of vectorsDoc.vectors) {
    it(`vector "${v.id}": canonical signable bytes match expected`, () => {
      const constitution = parseConstitution(v.input_constitution);
      const canonical = computeCanonicalSignableJson(constitution, 1);
      expect(canonical).toBe(v.expected_signable_canonical_json);
    });
  }
});

// ── cross-SDK signable byte-parity v2 (SAN-492) ──────────────────────

describe("CRITICAL: cross-SDK signable byte-parity v2 (SAN-492)", () => {
  const vectorsPath = resolve(FIXTURES, "constitution-signable-vectors-v2.json");
  const vectorsDoc = JSON.parse(readFileSync(vectorsPath, "utf-8")) as {
    signing_version: number;
    vectors: Array<{
      id: string;
      input_constitution: Record<string, unknown>;
      expected_signable_canonical_json: string;
      expected_signable_sha256: string;
    }>;
  };

  it("vectors file is signing_version 2", () => {
    expect(vectorsDoc.signing_version).toBe(2);
  });

  for (const v of vectorsDoc.vectors) {
    it(`vector "${v.id}": canonical signable bytes match expected (v2)`, () => {
      const constitution = parseConstitution(v.input_constitution);
      const canonical = computeCanonicalSignableJson(constitution, 2);
      expect(canonical).toBe(v.expected_signable_canonical_json);
    });
  }
});

// ── v1 backwards-compat verification canary (SAN-492) ────────────────

describe("CRITICAL: v1 backwards-compat verification (SAN-492)", () => {
  it("minimal.yaml (v1-signed) verifies under v1 dispatch", () => {
    const yamlPath = resolve(FIXTURES, "constitutions/minimal.yaml");
    const constitution = loadConstitution(yamlPath);
    expect(constitution.provenance.signature?.scheme).toBe("constitution_sig_v1");

    const publicKey = loadPublicKey(resolve(FIXTURES, "keypairs/test-author.pub"));
    expect(verifyConstitutionSignature(constitution, publicKey)).toBe(true);
  });
});
