/**
 * CRITICAL CROSS-LANGUAGE TEST
 *
 * Loads Python-generated receipt fixtures from spec/fixtures/receipts/
 * and verifies them with the TypeScript verifier. This proves that
 * receipts generated by the Python reference implementation can be
 * verified by the TypeScript SDK — the core promise of cross-language
 * receipt portability.
 *
 * Fixture fingerprint formulas:
 * - checks_version "5" (v1.0): 12-field formula, cannot recompute with 14-field code
 * - checks_version "6" + spec_version "1.1": legacy 14-field formula from pre-v1.0
 *   Python generator. The v1.2 spec documented a correction: the old spec docs listed
 *   spec_version/tool_version/timestamp/status/query_hash as fingerprint fields but
 *   the production implementations used correlation_id/context_hash/output_hash/etc.
 *   These fixtures were generated with the OLD documented formula. Fingerprint
 *   recomputation is skipped; signature and content hash verification still apply.
 * - Future fixtures generated by sanna>=1.0.0 or sanna-ts>=1.0.2 will use the
 *   corrected formula and pass full fingerprint recomputation.
 */

import { describe, it, expect } from "vitest";
import { resolve } from "node:path";
import { readFileSync, readdirSync } from "node:fs";
import { verifyReceipt } from "../src/verifier.js";
import { computeFingerprints } from "../src/receipt.js";
import { loadPublicKey } from "../src/crypto.js";
import { hashObj, hashContent, EMPTY_HASH } from "../src/hashing.js";

const FIXTURES = resolve(__dirname, "../../../spec/fixtures");
const golden = JSON.parse(
  readFileSync(resolve(FIXTURES, "golden-hashes.json"), "utf-8"),
);
const pubKey = loadPublicKey(resolve(FIXTURES, "keypairs/test-author.pub"));

// Load all receipt fixtures
const receiptDir = resolve(FIXTURES, "receipts");
const receiptFiles = readdirSync(receiptDir).filter((f) => f.endsWith(".json"));
const receipts: Record<string, Record<string, unknown>> = {};
for (const file of receiptFiles) {
  const name = file.replace(".json", "");
  receipts[name] = JSON.parse(readFileSync(resolve(receiptDir, file), "utf-8"));
}

/** v1.0 fixtures use 12-field fingerprint (checks_version "5") */
function isV1Fixture(receipt: Record<string, unknown>): boolean {
  return receipt.spec_version === "1.0" || receipt.checks_version === "5";
}

/**
 * Detect fixtures generated with the legacy fingerprint formula (pre-v1.0 Python).
 * These have checks_version "6" but their fingerprints were computed with
 * spec_version/tool_version/timestamp/status/query_hash as fields instead
 * of the corrected formula. We verify by recomputing with the legacy formula
 * and checking if it matches the stored fingerprint.
 */
function computeLegacyFingerprints(receipt: Record<string, unknown>): {
  receipt_fingerprint: string;
  full_fingerprint: string;
} {
  const inputs = receipt.inputs as Record<string, unknown> | undefined;
  const queryHash = inputs?.query
    ? hashContent(String(inputs.query), 64)
    : EMPTY_HASH;

  const checks = (receipt.checks as Record<string, unknown>[]) ?? [];
  const checksData = checks.map((c) => ({
    check_id: c.check_id ?? "",
    passed: c.passed,
    severity: c.severity ?? "",
    evidence: c.evidence ?? null,
  }));
  const checksHash = checksData.length > 0 ? hashObj(checksData) : EMPTY_HASH;

  const constitutionRef = receipt.constitution_ref as Record<string, unknown> | undefined;
  let constitutionHash = EMPTY_HASH;
  if (constitutionRef) {
    const stripped: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(constitutionRef)) {
      if (k !== "constitution_approval") stripped[k] = v;
    }
    constitutionHash = hashObj(stripped);
  }

  const extensions = receipt.extensions as Record<string, unknown> | undefined;
  const extensionsHash =
    extensions && Object.keys(extensions).length > 0
      ? hashObj(extensions)
      : EMPTY_HASH;

  const parentReceipts = receipt.parent_receipts as string[] | null | undefined;
  const parentReceiptsHash = parentReceipts != null ? hashObj(parentReceipts) : EMPTY_HASH;

  const workflowId = receipt.workflow_id as string | null | undefined;
  const workflowIdHash = workflowId != null ? hashContent(workflowId, 64) : EMPTY_HASH;

  const fpInput = [
    receipt.spec_version ?? "",
    receipt.tool_version ?? "",
    receipt.checks_version ?? "",
    receipt.timestamp ?? "",
    receipt.correlation_id ?? "",
    receipt.context_hash ?? "",
    receipt.output_hash ?? "",
    queryHash,
    constitutionHash,
    receipt.status ?? "",
    checksHash,
    extensionsHash,
    parentReceiptsHash,
    workflowIdHash,
  ].join("|");

  return {
    receipt_fingerprint: hashContent(fpInput, 16),
    full_fingerprint: hashContent(fpInput, 64),
  };
}

function usesLegacyFormula(receipt: Record<string, unknown>): boolean {
  if (isV1Fixture(receipt)) return false;
  const { receipt_fingerprint } = computeFingerprints(receipt);
  if (receipt_fingerprint === receipt.receipt_fingerprint) return false;
  const { receipt_fingerprint: legacyFp } = computeLegacyFingerprints(receipt);
  return legacyFp === receipt.receipt_fingerprint;
}

// ── Cross-language verification ──────────────────────────────────────

describe("CRITICAL: cross-language receipt verification", () => {
  for (const [name, receipt] of Object.entries(receipts)) {
    describe(`receipt: ${name}`, () => {
      if (isV1Fixture(receipt)) {
        it("signature verifies (Python-signed, TypeScript-verified)", () => {
          const result = verifyReceipt(receipt, pubKey);
          expect(result.checks_performed).toContain("signature");
          expect(
            result.errors.filter((e) => e.toLowerCase().includes("signature")),
          ).toEqual([]);
        });

        it("content hashes match (Python-computed, TypeScript-recomputed)", () => {
          const computedCtx = hashObj(receipt.inputs);
          const computedOut = hashObj(receipt.outputs);
          expect(computedCtx).toBe(receipt.context_hash);
          expect(computedOut).toBe(receipt.output_hash);
        });

        it("fingerprint recomputation skipped for v1.0 fixture (12→14 field transition)", () => {
          expect(receipt.checks_version).toBe("5");
        });
      } else if (usesLegacyFormula(receipt)) {
        // Pre-v1.0 fixtures: fingerprint uses old documented formula (v1.2 spec correction).
        // Signature and content hashes still verify; fingerprint verified with legacy formula.
        it("signature verifies (Python-signed, TypeScript-verified)", () => {
          const result = verifyReceipt(receipt, pubKey);
          expect(result.checks_performed).toContain("signature");
          expect(
            result.errors.filter((e) => e.toLowerCase().includes("signature")),
          ).toEqual([]);
        });

        it("fingerprint matches legacy formula (pre-v1.0 Python generator)", () => {
          const { receipt_fingerprint, full_fingerprint } =
            computeLegacyFingerprints(receipt);
          expect(receipt_fingerprint).toBe(receipt.receipt_fingerprint);
          expect(full_fingerprint).toBe(receipt.full_fingerprint);
        });

        it("content hashes match (Python-computed, TypeScript-recomputed)", () => {
          const computedCtx = hashObj(receipt.inputs);
          const computedOut = hashObj(receipt.outputs);
          expect(computedCtx).toBe(receipt.context_hash);
          expect(computedOut).toBe(receipt.output_hash);
        });
      } else {
        it("passes full verification with TypeScript verifier", () => {
          const result = verifyReceipt(receipt, pubKey);
          if (!result.valid) {
            console.error(`VERIFICATION FAILED for ${name}:`, result.errors);
          }
          expect(result.valid).toBe(true);
          expect(result.errors).toEqual([]);
        });

        it("signature verifies (Python-signed, TypeScript-verified)", () => {
          const result = verifyReceipt(receipt, pubKey);
          expect(result.checks_performed).toContain("signature");
          expect(
            result.errors.filter((e) => e.toLowerCase().includes("signature")),
          ).toEqual([]);
        });

        it("fingerprint matches (Python-computed, TypeScript-recomputed)", () => {
          const { receipt_fingerprint, full_fingerprint } =
            computeFingerprints(receipt);
          expect(receipt_fingerprint).toBe(receipt.receipt_fingerprint);
          expect(full_fingerprint).toBe(receipt.full_fingerprint);
        });

        it("content hashes match (Python-computed, TypeScript-recomputed)", () => {
          const computedCtx = hashObj(receipt.inputs);
          const computedOut = hashObj(receipt.outputs);
          expect(computedCtx).toBe(receipt.context_hash);
          expect(computedOut).toBe(receipt.output_hash);
        });
      }
    });
  }
});

// ── 14-field fingerprint unit tests ──────────────────────────────────

describe("14-field fingerprint", () => {
  it("null parent_receipts and workflow_id produce EMPTY_HASH fields", () => {
    const receipt = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
      parent_receipts: null,
      workflow_id: null,
    };
    const fp1 = computeFingerprints(receipt);

    // Same as without those fields entirely
    const receipt2 = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp2 = computeFingerprints(receipt2);
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });

  it("non-null parent_receipts changes fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      parent_receipts: ["abc123"],
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("non-null workflow_id changes fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      workflow_id: "wf-001",
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("content_mode does NOT change fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      content_mode: "redacted",
      content_mode_source: "local_config",
    });
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });

  it("different parent_receipts arrays produce different fingerprints", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints({
      ...base,
      parent_receipts: ["abc"],
    });
    const fp2 = computeFingerprints({
      ...base,
      parent_receipts: ["def"],
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("deterministic: same inputs produce same fingerprint", () => {
    const receipt = {
      correlation_id: "det-001",
      context_hash: "c".repeat(64),
      output_hash: "d".repeat(64),
      checks_version: "6",
      checks: [],
      parent_receipts: ["parent-fp-1"],
      workflow_id: "wf-det-001",
    };
    const fp1 = computeFingerprints(receipt);
    const fp2 = computeFingerprints(receipt);
    expect(fp1.receipt_fingerprint).toBe(fp2.receipt_fingerprint);
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });
});

// ── Golden hash values ───────────────────────────────────────────────

describe("CRITICAL: golden hash cross-verification", () => {
  for (const [name, goldenData] of Object.entries(
    golden.receipts as Record<string, Record<string, unknown>>,
  )) {
    const receipt = receipts[name];
    if (!receipt) continue;

    describe(`golden: ${name}`, () => {
      it("receipt_fingerprint matches golden", () => {
        expect(receipt.receipt_fingerprint).toBe(goldenData.receipt_fingerprint);
      });

      it("full_fingerprint matches golden", () => {
        expect(receipt.full_fingerprint).toBe(goldenData.full_fingerprint);
      });

      it("context_hash matches golden", () => {
        expect(receipt.context_hash).toBe(goldenData.context_hash);
      });

      it("output_hash matches golden", () => {
        expect(receipt.output_hash).toBe(goldenData.output_hash);
      });

      it("signature key_id matches golden", () => {
        const sig = receipt.receipt_signature as Record<string, unknown>;
        expect(sig.key_id).toBe(goldenData.signature_key_id);
      });

      it("status matches golden", () => {
        expect(receipt.status).toBe(goldenData.status);
      });

      it("checks_passed matches golden", () => {
        expect(receipt.checks_passed).toBe(goldenData.checks_passed);
      });

      it("checks_failed matches golden", () => {
        expect(receipt.checks_failed).toBe(goldenData.checks_failed);
      });
    });
  }
});
