/**
 * CRITICAL CROSS-LANGUAGE TEST
 *
 * Loads Python-generated receipt fixtures from spec/fixtures/receipts/
 * and verifies them with the TypeScript verifier. This proves that
 * receipts generated by the Python reference implementation can be
 * verified by the TypeScript SDK — the core promise of cross-language
 * receipt portability.
 *
 * v1.3 fixtures use the 16-field fingerprint formula (checks_version "8"):
 *   correlation_id | context_hash | output_hash | checks_version |
 *   checks_hash | constitution_hash | enforcement_hash | coverage_hash |
 *   authority_hash | escalation_hash | trust_hash | extensions_hash |
 *   parent_receipts_hash | workflow_id_hash |
 *   enforcement_surface_hash | invariants_scope_hash
 */

import { describe, it, expect } from "vitest";
import { resolve } from "node:path";
import { readFileSync, readdirSync } from "node:fs";
import { verifyReceipt } from "../src/verifier.js";
import { computeFingerprints, generateReceipt } from "../src/receipt.js";
import { loadPublicKey } from "../src/crypto.js";
import { hashObj } from "../src/hashing.js";

const FIXTURES = resolve(__dirname, "../../../spec/fixtures");
const golden = JSON.parse(
  readFileSync(resolve(FIXTURES, "golden-hashes.json"), "utf-8"),
);
const pubKey = loadPublicKey(resolve(FIXTURES, "keypairs/test-author.pub"));

// Load all receipt fixtures
const receiptDir = resolve(FIXTURES, "receipts");
const receiptFiles = readdirSync(receiptDir).filter((f) => f.endsWith(".json"));
const receipts: Record<string, Record<string, unknown>> = {};
for (const file of receiptFiles) {
  const name = file.replace(".json", "");
  receipts[name] = JSON.parse(readFileSync(resolve(receiptDir, file), "utf-8"));
}

// ── Cross-language verification ──────────────────────────────────────

describe("CRITICAL: cross-language receipt verification", () => {
  for (const [name, receipt] of Object.entries(receipts)) {
    describe(`receipt: ${name}`, () => {
      it("passes full verification with TypeScript verifier", () => {
        const result = verifyReceipt(receipt, pubKey);
        if (!result.valid) {
          console.error(`VERIFICATION FAILED for ${name}:`, result.errors);
        }
        expect(result.valid).toBe(true);
        expect(result.errors).toEqual([]);
      });

      it("signature verifies (Python-signed, TypeScript-verified)", () => {
        const result = verifyReceipt(receipt, pubKey);
        expect(result.checks_performed).toContain("signature");
        expect(
          result.errors.filter((e) => e.toLowerCase().includes("signature")),
        ).toEqual([]);
      });

      it("fingerprint matches (Python-computed, TypeScript-recomputed)", () => {
        const { receipt_fingerprint, full_fingerprint } =
          computeFingerprints(receipt);
        expect(receipt_fingerprint).toBe(receipt.receipt_fingerprint);
        expect(full_fingerprint).toBe(receipt.full_fingerprint);
      });

      it("content hashes match (Python-computed, TypeScript-recomputed)", () => {
        const computedCtx = hashObj(receipt.inputs);
        const computedOut = hashObj(receipt.outputs);
        expect(computedCtx).toBe(receipt.context_hash);
        expect(computedOut).toBe(receipt.output_hash);
      });
    });
  }
});

// ── 14-field fingerprint unit tests ──────────────────────────────────

describe("14-field fingerprint", () => {
  it("null parent_receipts and workflow_id produce EMPTY_HASH fields", () => {
    const receipt = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
      parent_receipts: null,
      workflow_id: null,
    };
    const fp1 = computeFingerprints(receipt);

    // Same as without those fields entirely
    const receipt2 = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp2 = computeFingerprints(receipt2);
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });

  it("non-null parent_receipts changes fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      parent_receipts: ["abc123"],
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("non-null workflow_id changes fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      workflow_id: "wf-001",
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("content_mode does NOT change fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      content_mode: "redacted",
      content_mode_source: "local_config",
    });
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });

  it("different parent_receipts arrays produce different fingerprints", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints({
      ...base,
      parent_receipts: ["abc"],
    });
    const fp2 = computeFingerprints({
      ...base,
      parent_receipts: ["def"],
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("deterministic: same inputs produce same fingerprint", () => {
    const receipt = {
      correlation_id: "det-001",
      context_hash: "c".repeat(64),
      output_hash: "d".repeat(64),
      checks_version: "6",
      checks: [],
      parent_receipts: ["parent-fp-1"],
      workflow_id: "wf-det-001",
    };
    const fp1 = computeFingerprints(receipt);
    const fp2 = computeFingerprints(receipt);
    expect(fp1.receipt_fingerprint).toBe(fp2.receipt_fingerprint);
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });
});

// ── Golden hash values ───────────────────────────────────────────────

describe("CRITICAL: golden hash cross-verification", () => {
  for (const [name, goldenData] of Object.entries(
    golden.receipts as Record<string, Record<string, unknown>>,
  )) {
    const receipt = receipts[name];
    if (!receipt) continue;

    describe(`golden: ${name}`, () => {
      it("receipt_fingerprint matches golden", () => {
        expect(receipt.receipt_fingerprint).toBe(goldenData.receipt_fingerprint);
      });

      it("full_fingerprint matches golden", () => {
        expect(receipt.full_fingerprint).toBe(goldenData.full_fingerprint);
      });

      it("context_hash matches golden", () => {
        expect(receipt.context_hash).toBe(goldenData.context_hash);
      });

      it("output_hash matches golden", () => {
        expect(receipt.output_hash).toBe(goldenData.output_hash);
      });

      it("signature key_id matches golden", () => {
        const sig = receipt.receipt_signature as Record<string, unknown>;
        expect(sig.key_id).toBe(goldenData.signature_key_id);
      });

      it("status matches golden", () => {
        expect(receipt.status).toBe(goldenData.status);
      });

      it("checks_passed matches golden", () => {
        expect(receipt.checks_passed).toBe(goldenData.checks_passed);
      });

      it("checks_failed matches golden", () => {
        expect(receipt.checks_failed).toBe(goldenData.checks_failed);
      });
    });
  }
});

// ── v1.3 cross-language parity (SAN-213 AC 13) ──────────────────────

describe("v1.3 cross-language parity (SAN-213 AC 13)", () => {
  // Locate v1.3 fixtures: all fixtures in receipts/ with checks_version >= "8"
  const v13Fixtures = receiptFiles.filter((f) => {
    const r = receipts[f.replace(".json", "")];
    if (!r) return false;
    const cv = parseInt(String(r.checks_version ?? "0"), 10);
    return !isNaN(cv) && cv >= 8;
  });

  if (v13Fixtures.length === 0) {
    it.skip("No v1.3 fixtures found (checks_version >= 8) — submodule may not have shipped them yet", () => {});
  } else {
    // (a) For each v1.3 fixture, run the TS verifier and assert clean result.
    for (const file of v13Fixtures) {
      const name = file.replace(".json", "");
      const receipt = receipts[name];

      describe(`v1.3 fixture: ${name}`, () => {
        it("passes full verification with TypeScript verifier", () => {
          const result = verifyReceipt(receipt, pubKey);
          if (!result.valid) {
            console.error(`V1.3 VERIFICATION FAILED for ${name}:`, result.errors);
          }
          expect(result.valid).toBe(true);
          expect(result.errors).toEqual([]);
        });

        it("checks_performed includes all required check types", () => {
          const result = verifyReceipt(receipt, pubKey);
          expect(result.checks_performed).toContain("schema");
          expect(result.checks_performed).toContain("fingerprint");
          expect(result.checks_performed).toContain("content_hashes");
          expect(result.checks_performed).toContain("status_consistency");
          expect(result.checks_performed).toContain("timestamp");
        });

        it("has enforcement_surface and invariants_scope (v1.3 required fields)", () => {
          expect(receipt.enforcement_surface).toBeTruthy();
          expect(receipt.invariants_scope).toBeTruthy();
        });
      });
    }
  }

  // (c) Round-trip test: generate a v1.3 receipt via TS, verify it.
  it("v1.3 round-trip: TS-generated receipt verifies clean", () => {
    const r = generateReceipt({
      correlation_id: "cross-lang-3c",
      inputs: {},
      outputs: {},
      checks: [
        { check_id: "C1", passed: true, severity: "info", evidence: null },
      ],
      enforcementSurface: "middleware",
      invariantsScope: "full",
    }) as unknown as Record<string, unknown>;

    const result = verifyReceipt(r);
    expect(result.valid).toBe(true);
    expect(result.errors).toEqual([]);
  });

  // (d) Negative test: mutate enforcement_surface, expect the exact error string.
  it("v1.3 negative: receipt with empty enforcement_surface produces exact error string", () => {
    if (v13Fixtures.length === 0) {
      // Fall back to generating one
      const r = generateReceipt({
        correlation_id: "cross-lang-3c-neg",
        inputs: {},
        outputs: {},
        checks: [
          { check_id: "C1", passed: true, severity: "info", evidence: null },
        ],
        enforcementSurface: "middleware",
        invariantsScope: "full",
      }) as unknown as Record<string, unknown>;
      r.enforcement_surface = "";
      const result = verifyReceipt(r);
      expect(result.valid).toBe(false);
      expect(result.errors).toContain(
        "v1.3+ receipt (checks_version >= 8) is missing required field: enforcement_surface",
      );
    } else {
      // Use the first v1.3 fixture, set enforcement_surface to empty string
      const name = v13Fixtures[0].replace(".json", "");
      const r = { ...receipts[name], enforcement_surface: "" };
      const result = verifyReceipt(r);
      expect(result.valid).toBe(false);
      expect(result.errors).toContain(
        "v1.3+ receipt (checks_version >= 8) is missing required field: enforcement_surface",
      );
    }
  });
});
